spring:
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 175.178.189.89:12208
        ip: 47.96.86.132

#logging:
#  file:
#    path: logs/
#  config: classpath:logback-spring.xml