spring:
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 175.178.189.89:12208

# Sa-Token配置
sa-token:
  token-name: Authorization
  timeout: 2592000
  activity-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: false
  is-read-cookie: false
  is-read-head: true
