server:
  port: 13000

spring:
  redis:
    database: 10
    port: 6379
    host: 47.96.86.132
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  application:
    name: yiyulihua-websocket

logging:
  level:
    com.yiyulihua.websocket.server: debug


# Sa-Token配置
sa-token:
  token-name: Authorization
  timeout: 2592000
  activity-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: false
  is-read-cookie: false
  is-read-head: true

# feign 配置
feign:
  client:
    config:
      default:
        connect-timeout: 60000
        read-timeout: 60000
        loggerLevel: full

#Feign负载均衡配置 配置全局超时时间 毫秒单位
ribbon:
  ConnectTimeout: 5000 #请求连接的超时时间，默认时间为1秒
  ReadTimeout: 5000 #请求处理的超时时间