server:
  port: 13000

spring:
  redis:
    database: 10
    port: 6379
    host: 47.96.86.132
  datasource:
    username: snbo
    password: 1234
    url: jdbc:mysql://175.178.189.89:12209/yiyulihua?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  application:
    name: yiyulihua-websocket

logging:
  level:
    com.yiyulihua.websocket.server: debug


# Sa-Token配置
sa-token:
  token-name: Authorization
  timeout: 2592000
  activity-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: false
  is-read-cookie: false
  is-read-head: true

# feign 配置
feign:
  client:
    config:
      default:
        connect-timeout: 60000
        read-timeout: 60000
        loggerLevel: full
