server:
  port: 14000

spring:
  redis:
    database: 10
    port: 6379
    host: 47.96.86.132
  datasource:
    username: snbo
    password: 1234
    url: jdbc:mysql://175.178.189.89:12209/yiyulihua?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  application:
    name: yiyulihua-order

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.yiyulihua.works.dao: debug

# Sa-Token配置
sa-token:
  token-name: Authorization
  timeout: 2592000
  activity-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: false
  is-read-cookie: false
  is-read-head: true


alipay:
  app-id: 2021000121666477
  seller-id: 2088621993200503
  gateway-url: https://openapi.alipaydev.com/gateway.do
  # 商户私钥
  merchant-private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCa/aBS8f6a6Xp/tHmvAUg2Vqnqds9SCOpRdVb0qvl0uMvDIqibkd1t5S8AOUs32/ijg5WPRHg5z7TCojzRAYjNX7cTf4G7cu94HZP7hdgLJs/tnoNw6oTNclp31vuLkHej8vdhIfU8LB5S1wNudYYZ7FYCVceXDv4mPum6fR+LtJ4WrR1c/aGXOufJzKzMeyyNy0FeJ2mCOFtxRsT4GiRZRv/NNMRryg5GK8GwYETymKFn4OxfKN6/o+E9llT0EGuzkZ+26nG+bzNU/aAggnTWX+nCyGU6NBJC7nOivnk6eIEeSxeoQRGtKzaLdG+EK5CnO2pFOk8WtvyTzSCyuGeTAgMBAAECggEAK8vVfPrC3lVxdxqxc+Fh3XD5zLZL+TtpsyD8NGEH4pLBiV+G04cRUhd8A40tExjGlrX9EiHf8z4dLw6XLtxHIvmUCx9xsl1VC9UX1vBIT0ZlZRjwvXyXkFJq/Ag0xohJNnvWqYzl9l3lJ7V4U8ND5Jli6IACyU3ERVxrwXXP7zLkFF3TFSsqv+U+tCZQI70nlWKZQYEAl9fC92ITn/bdloGWCQ5lBewNOlZwKl4E+OqTJQ3t+NwfHyZXGX3jenmTpZgiDn9fznxHaFan5U3Gzz+kxowku43kIPI0vREj3/g7GOp2AGgr7KqH+fkOnvuesI09wtB4Ds8SPcWZCp6hKQKBgQD6tTmiXvIu9IBBpY5dFQUHnbALywvDyZXjkNUDjy8NFVreRZvG2CBZTDMjEEV90NflE8D34y7NBORvQKnWmWF8M72H8cu88UrNx2FgfXdeOM6wq+AL0Qf8QKH5xxTg3a5kpxwiw76aGSVsZcshgdZKT7JjPHTv5MMlNue/bEjK1wKBgQCeQyox8sZmXAHmzZi6Uud+Yht6FUukRZps8LNLFDNFMjY+8ABq/I5ASSTOjf46M2Jf6KwyCzrcZOWKLoJlxVFxz/siuTKw566wm2RCdRykjmkJj6iCAE+vrMDgG5WtFSPd/peTN3L3WjSyvJnpKkQqZuh5s1n92F+fnULYHS1NpQKBgFOpklga8xq0QPCnPMDXONx3xL3KvlxRsxFDzbHoYD0veSlfdUJ/8RubkB0NWwNHZCRv2R9f0shb75corwSMHroB0ifBism8g8fz1w0KEYGB14ehc5y93rpRHzxpMRBxKbcxBPSc+cgWyCRKO+UsnMQjoFX5YNSFNJIApol8qzX1AoGAZA6erLmKycg9w4gUmSg1B2hLauHv0snWmi2LjVoWGBdoyF3AReOqo+YaiSSoqG84MN7Pj0weSJzZqoVBF8qqdURCyG9CJyoy/aEgwAt+smL+8XaL2LUNrEmSH54RAT6uUHnXptGVs+CqFJ68x/da5VvuepLzwFN+EVHBoxS/QakCgYEAkajjdW7A8vC3Fo/jQk0wcHhgzSJwMs+qcJVMAgQOGKMhvwFhU+uo0eH96xqXtPb5UNd2IQd06OtP695InruAHMXCpKHKMZYr+4TEe9IXfqfRgPJby4fUiyHvyp8W5CMXHjY3qjH6dfLmZIZbqIqeLsmyu2n5vpGhfroJorAmLe0=
  # 支付宝公钥
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAl90kZJOGvNQcU1gj5Fn1/8uPXZ9PLb+rkQgcTSTf94BOER5kWqtsBtJH5Yn78cxGT53lwZFuPc3nzy7r57dnGYlNsh+0eM04mXfeEQmwhsKAT99V8qNy/lsaVyvuYNVxL7v62bjHkw0wGUgiflB1kbOhafnK/Xxkdj1W7HTdvMG7XBaK33HS6er/K/EjfbCnxzPElxv/82Zh8G/Utr0Q88z8ym6zfXRBU8gArZR+vxbp4UHGHAppsqk8eZsfQsEvaU/B3BeFa5xYMMMmjDmj00h5DKylnv8HJoIJSPzgVoShnJGa666pmJT4hj22J1IfSaGAfA673/xYTFUYXxLuXwIDAQAB
  # 接口内容加密对称秘钥
  content-key: f/MzD+zLPaWQPRz7zVHz3A==
  # 页面跳转同步通知页面路径 需http://格式的完整路径，不能加?id=123这类自定义参数，必须外网可以正常访问
  return-url: http://工程公网访问地址/alipay.trade.page.pay-JAVA-UTF-8/return_url.jsp
  # 服务器异步通知页面路径  需http://格式的完整路径，不能加?id=123这类自定义参数，必须外网可以正常访问
  notify-url: http://工程公网访问地址/alipay.trade.page.pay-JAVA-UTF-8/notify_url.jsp
