server:
  port: 88

spring:
  application:
    name: yiyulihua-gateway
  redis:
    database: 10
    port: 6379
    host: 47.96.86.132
  cloud:
    nacos:
      discovery:
        server-addr: 175.178.189.89:12208
    gateway:
      routes:
        - id: task_route  #任务模块路由
          uri: lb://yiyulihua-task
          predicates:
            - Path=/api/task/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}
            - Log

        - id: task_user  # 用户模块路由
          uri: lb://yiyulihua-user
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}
            - Log

        - id: yiyulihua-works
          uri: lb://yiyulihua-works
          predicates:
            - Path=/work/**

        - id: yiyulihua-oss
          uri: lb://yiyulihua-oss
          predicates:
            - Path=/oss/**

# Sa-Token配置
sa-token:
  token-name: Authorization
  timeout: 2592000
  activity-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: false
  is-read-cookie: false
  is-read-head: true
