server:
  port: 88

spring:
  application:
    name: yiyulihua-gateway
  redis:
    database: 10
    port: 6379
    host: 47.96.86.132
  cloud:
    nacos:
      discovery:
        server-addr: 175.178.189.89:12208
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写
      routes:
        - id: auth_route  #认证模块路由
          uri: lb://yiyulihua-auth
          predicates:
            - Path=/api-auth/**
          filters:
            - StripPrefix=1
            - Log

        - id: task_route  #任务模块路由
          uri: lb://yiyulihua-task
          predicates:
            - Path=/api-task/**
          filters:
            - StripPrefix=1
            - Log

        - id: user_route  # 用户模块路由
          uri: lb://yiyulihua-user
          predicates:
            - Path=/api-user/**
          filters:
            - StripPrefix=1
            - Log

        - id: works_route #作品模块路由
          uri: lb://yiyulihua-works
          predicates:
            - Path=/api-works/**
          filters:
            - StripPrefix=1
            - Log

        - id: oss-route
          uri: lb://yiyulihua-oss
          predicates:
            - Path=/api-oss/**
          filters:
            - StripPrefix=1
            - Log



# Sa-Token配置
sa-token:
  token-name: Authorization
  timeout: 2592000
  activity-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: false
  is-read-cookie: false
  is-read-head: true
