server:
  port: 88

spring:
  application:
    name: yiyulihua-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 175.178.189.89:12208
    gateway:
      routes:
        - id: task_route  #任务模块路由
          uri: lb://yiyulihua-task
          predicates:
            - Path=/api/task/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}
            - Log

        - id: task_user  # 用户模块路由
          uri: lb://yiyulihua-user
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}
            - Log

        - id: yiyulihua-works
          uri: lb://yiyulihua-works
          predicates:
            - Path=/work/**

        - id: yiyulihua-oss
          uri: lb://yiyulihua-oss
          predicates:
            - Path=/oss/**

