server:
  port: 88

spring:
  application:
    name: yiyulihua-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 47.96.86.132:8848
    gateway:
      routes:
        - id: task_route  #任务模块路由
          uri: lb://yiyulihua-task
          predicates:
            - Path=/api/task/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}


