server:
  port: 88

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: client_route
          uri: lb://jywclient       #客户端服务
          predicates:
            - Path=/api/jywclient/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}


